
name: Build dockerimage

on:
  push:
    tags:
      - "*"

jobs:
  publish-docker:
    name: Build dockerimage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install docker
        uses: docker-practice/actions-setup-docker@master
      - name: install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      - run: |
          sh production.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-world Docker image
        run: |
          docker tag school-notes-next:latest ghcr.io/$username/school-notes-next:latest
          docker push ghcr.io/$username/school-notes-next:latest
        env:
          username: ${{ github.actor }}

      # - name: Updaload docker_image
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ./school-notes-next_dockerimage.tar
      #     tag: ${{ github.ref }}
